
export const GITHUB_USERNAME = "Ahmed-Emad-Nasr";

export const knowledgeEducationItems = [
  {
    tag: "Incident Response Analyst Intern",
    subTag: "Digital Egypt Pioneers Initiative (DEPI)",
    subTagHyperlink: "https://www.depi.gov.eg/",
    desc: "Completed a 6-month DEPI training program, solving TryHackMe labs that simulate the full Incident Response (IR) lifecycle. Implemented a DEPI graduation project using ELK SIEM, Wazuh EDR, and Suricata, reducing false positive alerts by 9%.",
    isRight: true,
    startDate: "2026-01-01",
    showDate: true,
  },
  {
    tag: "Information Security Analyst Intern",
    subTag: "Digital Egypt Pioneers Initiative (DEPI)",
    subTagHyperlink: "https://www.depi.gov.eg/",
    desc: "Analyzed and triaged simulated security alerts within TryHackMe environments, applying core SOC lifecycle methodologies. Developed a DEPI capstone project using Wazuh, Suricata, VirusTotal, and YARA rules, increasing detection capabilities by 12%.",
    isRight: false,
    startDate: "2025-06-01",
    endDate: "2025-12-01",
    showDate: true,
  },
  {
    tag: "Volunteer Cybersecurity Instructor & Technical Trainer",
    subTag: "Google Developers Group (GDG) and Science In Code (SIC)",
    subTagHyperlink: "https://gdg.community.dev/",
    desc: "Delivered cybersecurity training to 120+ learners, resulting in a 40% improvement in practical skills and rating of 4.9/5.",
    isRight: true,
    startDate: "2024-10-01",
    endDate: "2025-10-01",
    showDate: true,
  },
  {
    tag: "Bachelor of Computer Science",
    desc: "Major: Information Security and Digital Forensics | GPA: 3.7/4.0",
    subTag: "Benha University",
    subTagHyperlink: "https://www.bu.edu.eg/",
    isRight: false,
    startDate: "2022-10-01",
    endDate: "2026-07-01",
    showDate: true,
  },
  {
    tag: "Cybertalents Penetration Testing Bootcamp",
    subTag: "Cybertalents",
    subTagHyperlink: "https://cybertalents.com/",
    desc: "Completed intensive penetration testing training program.",
    isRight: true,
    startDate: "2025-11-01",
    endDate: "2025-12-01",
    showDate: true,
  },
  {
    tag: "ITI Summer Cybersecurity Program",
    subTag: "Information Technology Institute",
    subTagHyperlink: "https://www.iti.gov.eg/",
    desc: "Comprehensive cybersecurity training and hands-on labs.",
    isRight: false,
    startDate: "2025-09-01",
    endDate: "2025-11-01",
    showDate: true,
  },
  {
    tag: "Arabic Language",
    desc: "Native speaker with strong language proficiency.",
    isRight: true,
    startDate: "2019-01-01",
    showDate: false,
  },
  {
    tag: "English Language",
    desc: "Professional Working Proficiency (C1) - Strong in speaking, writing, and technical communication.",
    isRight: false,
    startDate: "2019-01-01",
    showDate: false,
  },
];
